homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 59.4118
  longitude: 17.6167
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  #Customize
  customize: !include customize.yaml
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

hassio:
frontend:
config:
updater:
history:
logbook:
sun:


# Text to speech
#tts:
#  - platform: google

# Cloud
cloud:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.111.211:3218

sensor:
- platform: yr
  monitored_conditions:
  - symbol
  - humidity
  - temperature
- platform: time_date
  display_options:
  - 'time'
  - 'time_utc'
- platform: mqtt
  name: 'ESP01rssi'
  state_topic: '/ESP01/wifi/RSSI'
- platform: mqtt
  name: 'ESP02rssi'
  state_topic: '/ESP02/wifi/RSSI'
- platform: mqtt
  name: 'ESP03rssi'
  state_topic: '/ESP03/wifi/RSSI'
- platform: mqtt
  name: 'ESP04rssi'
  state_topic: '/ESP04/wifi/RSSI'
- platform: mqtt
  name: 'ESP05rssi'
  state_topic: '/ESP05/wifi/RSSI'
- platform: mqtt
  name: 'GarageTempELC'
  state_topic: '/ESP04/Temp/ELC1'
- platform: mqtt
  name: 'HouseTempELC1'
  state_topic: '/ESP05/Temp/Garage'
   
light:
- platform: mqtt
  name: 'EbbaFasad'
  state_topic: '/ESP01/Relay/RL1'
  command_topic: '/ESP01/gpio/12'
  payload_on: "1"
  payload_off: "0" 
  state_on: "1"
  state_off: "0"
#  retain: true
- platform: mqtt
  name: 'ESP02_RL'
  state_topic: '/ESP02/Relay/RL1'
  command_topic: '/ESP02/gpio/12'
  payload_on: "1"
  payload_off: "0" 
  state_on: "1"
  state_off: "0"
#  retain: true
- platform: mqtt
  name: 'ESP03_RL'
  state_topic: '/ESP03/Relay/RL1'
  command_topic: '/ESP03/gpio/12'
  payload_on: "1"
  payload_off: "0" 
  state_on: "1"
  state_off: "0"
  retain: true
- platform: mqtt
  name: 'GarageFasad'
  state_topic: '/ESP04/Relay/RL1'
  command_topic: '/ESP04/gpio/12'
  payload_on: "1"
  payload_off: "0"
  state_on: "1"
  state_off: "0"
  retain: true
- platform: mqtt
  name: 'HouseWindow1'
  state_topic: '/ESP05/Relay/RL1'
  command_topic: '/ESP05/gpio/12'
  payload_on: "1"
  payload_off: "0"
  state_on: "1"
  state_off: "0"
  retain: true

scene:
  - name: GardenOn
    entities:
      light.EbbaFasad: on
      light.ESP02_RL: on
      light.ESP03_RL: on
      light.HouseWindow1: on
      light.GarageFasad: on
  - name: GardenOff
    entities:
      light.EbbaFasad: off
      light.ESP02_RL: off
      light.ESP03_RL: off
      light.HouseWindow1: off
      light.GarageFasad: off
  
mqtt:
  password: !secret mqtt_password
