homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 59.4118
  longitude: 17.6167
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

hassio:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr
    monitored_conditions:
      - symbol
      - humidity
      - temperature
  - platform: time_date
    display_options:
      - 'time'
      - 'time_utc'

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.111.211:3218
    
light:
- platform: mqtt
  name: 'EbbaFasad'
#  entity_id: '/ESP01_RL1'
  state_topic: '/ESP01/Relay/RL1'
  command_topic: '/ESP01/gpio/12'
  payload_on: "1"
  payload_off: "0" 
#  retain: true

# light 2:
- platform: mqtt
  name: 'ESP02 RL'
#  entity_id: '/ESP02_RL1'
  state_topic: '/ESP02/Relay/RL1'
  command_topic: '/ESP02/gpio/12'
  payload_on: "1"
  payload_off: "0" 
  retain: true

# light 3:
- platform: mqtt
  name: 'ESP03 RL'
  entity_id: '/ESP03_RL1'
  state_topic: '/ESP03/Relay/RL1'
  command_topic: '/ESP03/gpio/12'
  payload_on: "1"
  payload_off: "0" 
#  retain: true

# light 4:
- platform: mqtt
  name: 'HouseWindow1'
  entity_id: '/house_window1'
  state_topic: '/ELC1_1/Light/Window'
  command_topic: '/ELC1_1/gpio/12'
  payload_on: "1"
  payload_off: "0"
  retain: true
  
# light 5:
- platform: mqtt
  name: 'GarageFasad'
  entity_id: '/garage_fasad'
  state_topic: '/ELCG_1/Light/Fasad'
  command_topic: '/ELCG_1/gpio/12'
  payload_on: "1"
  payload_off: "0"
  retain: true

sensor 3:
  platform: mqtt
  name: 'ELC1_1RSSI'
  entity_id: '/elc11rssi'
  state_topic: '/ELC1_1/WiFi/RSSI'

sensor 4:
  platform: mqtt
  name: 'ELCG_1RSSI'
  entity_id: '/elcg1rssi'
  state_topic: '/ELCG_1/WiFi/RSSI'

sensor 5:
  platform: mqtt
  name: 'ESP01_RSSI'
  entity_id: '/ESP01_RSSI'
  state_topic: '/ESP01/wifi/RSSI'

sensor 6:
  platform: mqtt
  name: 'HouseTempELC1'
  entity_id: '/housetempelc1'
  state_topic: '/ELC1_1/Temp/ELC1'

sensor 7:
  platform: mqtt
  name: 'GarageTempELC'
  entity_id: '/garagetempelc1'
  state_topic: '/ELCG_1/Temp/Garage'

scene:
  - name: GardenOn
    entities:
      light.EbbaFasad: on
      light.HouseWindow1: on
      light.GarageFasad: on
  - name: GardenOff
    entities:
      light.EbbaFasad: off
      light.HouseWindow1: off
      light.GarageFasad: off
  
mqtt:
  password: !secret mqtt_password
